<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend/proto/echo.proto

namespace GPBMetadata\Backend\Proto;

class PBEcho
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
—
backend/proto/echo.proto"
EchoRequest
message (	"
EchoResponse
message (	22
EchoService#
Ping.EchoRequest.EchoResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

